// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/saved_tensor_slice.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/util/saved_tensor_slice.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {

namespace {

const ::google::protobuf::Descriptor* SavedSliceMeta_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SavedSliceMeta_reflection_ = NULL;
const ::google::protobuf::Descriptor* SavedTensorSliceMeta_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SavedTensorSliceMeta_reflection_ = NULL;
const ::google::protobuf::Descriptor* SavedSlice_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SavedSlice_reflection_ = NULL;
const ::google::protobuf::Descriptor* SavedTensorSlices_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SavedTensorSlices_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto() {
  protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow/core/util/saved_tensor_slice.proto");
  GOOGLE_CHECK(file != NULL);
  SavedSliceMeta_descriptor_ = file->message_type(0);
  static const int SavedSliceMeta_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, shape_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, slice_),
  };
  SavedSliceMeta_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SavedSliceMeta_descriptor_,
      SavedSliceMeta::default_instance_,
      SavedSliceMeta_offsets_,
      -1,
      -1,
      -1,
      sizeof(SavedSliceMeta),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSliceMeta, _is_default_instance_));
  SavedTensorSliceMeta_descriptor_ = file->message_type(1);
  static const int SavedTensorSliceMeta_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSliceMeta, tensor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSliceMeta, versions_),
  };
  SavedTensorSliceMeta_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SavedTensorSliceMeta_descriptor_,
      SavedTensorSliceMeta::default_instance_,
      SavedTensorSliceMeta_offsets_,
      -1,
      -1,
      -1,
      sizeof(SavedTensorSliceMeta),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSliceMeta, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSliceMeta, _is_default_instance_));
  SavedSlice_descriptor_ = file->message_type(2);
  static const int SavedSlice_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSlice, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSlice, slice_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSlice, data_),
  };
  SavedSlice_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SavedSlice_descriptor_,
      SavedSlice::default_instance_,
      SavedSlice_offsets_,
      -1,
      -1,
      -1,
      sizeof(SavedSlice),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSlice, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedSlice, _is_default_instance_));
  SavedTensorSlices_descriptor_ = file->message_type(3);
  static const int SavedTensorSlices_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSlices, meta_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSlices, data_),
  };
  SavedTensorSlices_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SavedTensorSlices_descriptor_,
      SavedTensorSlices::default_instance_,
      SavedTensorSlices_offsets_,
      -1,
      -1,
      -1,
      sizeof(SavedTensorSlices),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSlices, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SavedTensorSlices, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SavedSliceMeta_descriptor_, &SavedSliceMeta::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SavedTensorSliceMeta_descriptor_, &SavedTensorSliceMeta::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SavedSlice_descriptor_, &SavedSlice::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SavedTensorSlices_descriptor_, &SavedTensorSlices::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto() {
  delete SavedSliceMeta::default_instance_;
  delete SavedSliceMeta_reflection_;
  delete SavedTensorSliceMeta::default_instance_;
  delete SavedTensorSliceMeta_reflection_;
  delete SavedSlice::default_instance_;
  delete SavedSlice_reflection_;
  delete SavedTensorSlices::default_instance_;
  delete SavedTensorSlices_reflection_;
}

void protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2ftensor_5fshape_2eproto();
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2ftensor_5fslice_2eproto();
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2ftensor_2eproto();
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2ftypes_2eproto();
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2fversions_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n-tensorflow/core/util/saved_tensor_slic"
    "e.proto\022\ntensorflow\032,tensorflow/core/fra"
    "mework/tensor_shape.proto\032,tensorflow/co"
    "re/framework/tensor_slice.proto\032&tensorf"
    "low/core/framework/tensor.proto\032%tensorf"
    "low/core/framework/types.proto\032(tensorfl"
    "ow/core/framework/versions.proto\"\234\001\n\016Sav"
    "edSliceMeta\022\014\n\004name\030\001 \001(\t\022+\n\005shape\030\002 \001(\013"
    "2\034.tensorflow.TensorShapeProto\022\"\n\004type\030\003"
    " \001(\0162\024.tensorflow.DataType\022+\n\005slice\030\004 \003("
    "\0132\034.tensorflow.TensorSliceProto\"l\n\024Saved"
    "TensorSliceMeta\022*\n\006tensor\030\001 \003(\0132\032.tensor"
    "flow.SavedSliceMeta\022(\n\010versions\030\002 \001(\0132\026."
    "tensorflow.VersionDef\"n\n\nSavedSlice\022\014\n\004n"
    "ame\030\001 \001(\t\022+\n\005slice\030\002 \001(\0132\034.tensorflow.Te"
    "nsorSliceProto\022%\n\004data\030\003 \001(\0132\027.tensorflo"
    "w.TensorProto\"i\n\021SavedTensorSlices\022.\n\004me"
    "ta\030\001 \001(\0132 .tensorflow.SavedTensorSliceMe"
    "ta\022$\n\004data\030\002 \001(\0132\026.tensorflow.SavedSlice"
    "B/\n\023org.tensorflow.utilB\026SavedTensorSlic"
    "eProtosP\001b\006proto3", 817);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/util/saved_tensor_slice.proto", &protobuf_RegisterTypes);
  SavedSliceMeta::default_instance_ = new SavedSliceMeta();
  SavedTensorSliceMeta::default_instance_ = new SavedTensorSliceMeta();
  SavedSlice::default_instance_ = new SavedSlice();
  SavedTensorSlices::default_instance_ = new SavedTensorSlices();
  SavedSliceMeta::default_instance_->InitAsDefaultInstance();
  SavedTensorSliceMeta::default_instance_->InitAsDefaultInstance();
  SavedSlice::default_instance_->InitAsDefaultInstance();
  SavedTensorSlices::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SavedSliceMeta::kNameFieldNumber;
const int SavedSliceMeta::kShapeFieldNumber;
const int SavedSliceMeta::kTypeFieldNumber;
const int SavedSliceMeta::kSliceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SavedSliceMeta::SavedSliceMeta()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.SavedSliceMeta)
}

void SavedSliceMeta::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  shape_ = const_cast< ::tensorflow::TensorShapeProto*>(&::tensorflow::TensorShapeProto::default_instance());
}

SavedSliceMeta::SavedSliceMeta(const SavedSliceMeta& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.SavedSliceMeta)
}

void SavedSliceMeta::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shape_ = NULL;
  type_ = 0;
}

SavedSliceMeta::~SavedSliceMeta() {
  // @@protoc_insertion_point(destructor:tensorflow.SavedSliceMeta)
  SharedDtor();
}

void SavedSliceMeta::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete shape_;
  }
}

void SavedSliceMeta::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SavedSliceMeta::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SavedSliceMeta_descriptor_;
}

const SavedSliceMeta& SavedSliceMeta::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  return *default_instance_;
}

SavedSliceMeta* SavedSliceMeta::default_instance_ = NULL;

SavedSliceMeta* SavedSliceMeta::New(::google::protobuf::Arena* arena) const {
  SavedSliceMeta* n = new SavedSliceMeta;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SavedSliceMeta::Clear() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && shape_ != NULL) delete shape_;
  shape_ = NULL;
  type_ = 0;
  slice_.Clear();
}

bool SavedSliceMeta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.SavedSliceMeta)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.SavedSliceMeta.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_shape;
        break;
      }

      // optional .tensorflow.TensorShapeProto shape = 2;
      case 2: {
        if (tag == 18) {
         parse_shape:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_shape()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_type;
        break;
      }

      // optional .tensorflow.DataType type = 3;
      case 3: {
        if (tag == 24) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::tensorflow::DataType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_slice;
        break;
      }

      // repeated .tensorflow.TensorSliceProto slice = 4;
      case 4: {
        if (tag == 34) {
         parse_slice:
          DO_(input->IncrementRecursionDepth());
         parse_loop_slice:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_slice()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_slice;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.SavedSliceMeta)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.SavedSliceMeta)
  return false;
#undef DO_
}

void SavedSliceMeta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.SavedSliceMeta)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.SavedSliceMeta.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional .tensorflow.TensorShapeProto shape = 2;
  if (this->has_shape()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->shape_, output);
  }

  // optional .tensorflow.DataType type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // repeated .tensorflow.TensorSliceProto slice = 4;
  for (unsigned int i = 0, n = this->slice_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->slice(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.SavedSliceMeta)
}

::google::protobuf::uint8* SavedSliceMeta::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.SavedSliceMeta)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.SavedSliceMeta.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional .tensorflow.TensorShapeProto shape = 2;
  if (this->has_shape()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->shape_, target);
  }

  // optional .tensorflow.DataType type = 3;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->type(), target);
  }

  // repeated .tensorflow.TensorSliceProto slice = 4;
  for (unsigned int i = 0, n = this->slice_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->slice(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.SavedSliceMeta)
  return target;
}

int SavedSliceMeta::ByteSize() const {
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional .tensorflow.TensorShapeProto shape = 2;
  if (this->has_shape()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->shape_);
  }

  // optional .tensorflow.DataType type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // repeated .tensorflow.TensorSliceProto slice = 4;
  total_size += 1 * this->slice_size();
  for (int i = 0; i < this->slice_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->slice(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SavedSliceMeta::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SavedSliceMeta* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SavedSliceMeta>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SavedSliceMeta::MergeFrom(const SavedSliceMeta& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  slice_.MergeFrom(from.slice_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_shape()) {
    mutable_shape()->::tensorflow::TensorShapeProto::MergeFrom(from.shape());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void SavedSliceMeta::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SavedSliceMeta::CopyFrom(const SavedSliceMeta& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SavedSliceMeta::IsInitialized() const {

  return true;
}

void SavedSliceMeta::Swap(SavedSliceMeta* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SavedSliceMeta::InternalSwap(SavedSliceMeta* other) {
  name_.Swap(&other->name_);
  std::swap(shape_, other->shape_);
  std::swap(type_, other->type_);
  slice_.UnsafeArenaSwap(&other->slice_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SavedSliceMeta::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SavedSliceMeta_descriptor_;
  metadata.reflection = SavedSliceMeta_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SavedSliceMeta

// optional string name = 1;
void SavedSliceMeta::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SavedSliceMeta::name() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSliceMeta.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SavedSliceMeta::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.SavedSliceMeta.name)
}
 void SavedSliceMeta::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.SavedSliceMeta.name)
}
 void SavedSliceMeta::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.SavedSliceMeta.name)
}
 ::std::string* SavedSliceMeta::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSliceMeta.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SavedSliceMeta::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SavedSliceMeta::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedSliceMeta.name)
}

// optional .tensorflow.TensorShapeProto shape = 2;
bool SavedSliceMeta::has_shape() const {
  return !_is_default_instance_ && shape_ != NULL;
}
void SavedSliceMeta::clear_shape() {
  if (GetArenaNoVirtual() == NULL && shape_ != NULL) delete shape_;
  shape_ = NULL;
}
const ::tensorflow::TensorShapeProto& SavedSliceMeta::shape() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSliceMeta.shape)
  return shape_ != NULL ? *shape_ : *default_instance_->shape_;
}
::tensorflow::TensorShapeProto* SavedSliceMeta::mutable_shape() {
  
  if (shape_ == NULL) {
    shape_ = new ::tensorflow::TensorShapeProto;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSliceMeta.shape)
  return shape_;
}
::tensorflow::TensorShapeProto* SavedSliceMeta::release_shape() {
  
  ::tensorflow::TensorShapeProto* temp = shape_;
  shape_ = NULL;
  return temp;
}
void SavedSliceMeta::set_allocated_shape(::tensorflow::TensorShapeProto* shape) {
  delete shape_;
  shape_ = shape;
  if (shape) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedSliceMeta.shape)
}

// optional .tensorflow.DataType type = 3;
void SavedSliceMeta::clear_type() {
  type_ = 0;
}
 ::tensorflow::DataType SavedSliceMeta::type() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSliceMeta.type)
  return static_cast< ::tensorflow::DataType >(type_);
}
 void SavedSliceMeta::set_type(::tensorflow::DataType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.SavedSliceMeta.type)
}

// repeated .tensorflow.TensorSliceProto slice = 4;
int SavedSliceMeta::slice_size() const {
  return slice_.size();
}
void SavedSliceMeta::clear_slice() {
  slice_.Clear();
}
const ::tensorflow::TensorSliceProto& SavedSliceMeta::slice(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSliceMeta.slice)
  return slice_.Get(index);
}
::tensorflow::TensorSliceProto* SavedSliceMeta::mutable_slice(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSliceMeta.slice)
  return slice_.Mutable(index);
}
::tensorflow::TensorSliceProto* SavedSliceMeta::add_slice() {
  // @@protoc_insertion_point(field_add:tensorflow.SavedSliceMeta.slice)
  return slice_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::TensorSliceProto >*
SavedSliceMeta::mutable_slice() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.SavedSliceMeta.slice)
  return &slice_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::TensorSliceProto >&
SavedSliceMeta::slice() const {
  // @@protoc_insertion_point(field_list:tensorflow.SavedSliceMeta.slice)
  return slice_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SavedTensorSliceMeta::kTensorFieldNumber;
const int SavedTensorSliceMeta::kVersionsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SavedTensorSliceMeta::SavedTensorSliceMeta()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.SavedTensorSliceMeta)
}

void SavedTensorSliceMeta::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  versions_ = const_cast< ::tensorflow::VersionDef*>(&::tensorflow::VersionDef::default_instance());
}

SavedTensorSliceMeta::SavedTensorSliceMeta(const SavedTensorSliceMeta& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.SavedTensorSliceMeta)
}

void SavedTensorSliceMeta::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  versions_ = NULL;
}

SavedTensorSliceMeta::~SavedTensorSliceMeta() {
  // @@protoc_insertion_point(destructor:tensorflow.SavedTensorSliceMeta)
  SharedDtor();
}

void SavedTensorSliceMeta::SharedDtor() {
  if (this != default_instance_) {
    delete versions_;
  }
}

void SavedTensorSliceMeta::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SavedTensorSliceMeta::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SavedTensorSliceMeta_descriptor_;
}

const SavedTensorSliceMeta& SavedTensorSliceMeta::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  return *default_instance_;
}

SavedTensorSliceMeta* SavedTensorSliceMeta::default_instance_ = NULL;

SavedTensorSliceMeta* SavedTensorSliceMeta::New(::google::protobuf::Arena* arena) const {
  SavedTensorSliceMeta* n = new SavedTensorSliceMeta;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SavedTensorSliceMeta::Clear() {
  if (GetArenaNoVirtual() == NULL && versions_ != NULL) delete versions_;
  versions_ = NULL;
  tensor_.Clear();
}

bool SavedTensorSliceMeta::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.SavedTensorSliceMeta)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.SavedSliceMeta tensor = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_tensor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_tensor()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_tensor;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(18)) goto parse_versions;
        break;
      }

      // optional .tensorflow.VersionDef versions = 2;
      case 2: {
        if (tag == 18) {
         parse_versions:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_versions()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.SavedTensorSliceMeta)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.SavedTensorSliceMeta)
  return false;
#undef DO_
}

void SavedTensorSliceMeta::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.SavedTensorSliceMeta)
  // repeated .tensorflow.SavedSliceMeta tensor = 1;
  for (unsigned int i = 0, n = this->tensor_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->tensor(i), output);
  }

  // optional .tensorflow.VersionDef versions = 2;
  if (this->has_versions()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->versions_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.SavedTensorSliceMeta)
}

::google::protobuf::uint8* SavedTensorSliceMeta::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.SavedTensorSliceMeta)
  // repeated .tensorflow.SavedSliceMeta tensor = 1;
  for (unsigned int i = 0, n = this->tensor_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->tensor(i), target);
  }

  // optional .tensorflow.VersionDef versions = 2;
  if (this->has_versions()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->versions_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.SavedTensorSliceMeta)
  return target;
}

int SavedTensorSliceMeta::ByteSize() const {
  int total_size = 0;

  // optional .tensorflow.VersionDef versions = 2;
  if (this->has_versions()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->versions_);
  }

  // repeated .tensorflow.SavedSliceMeta tensor = 1;
  total_size += 1 * this->tensor_size();
  for (int i = 0; i < this->tensor_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->tensor(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SavedTensorSliceMeta::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SavedTensorSliceMeta* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SavedTensorSliceMeta>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SavedTensorSliceMeta::MergeFrom(const SavedTensorSliceMeta& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  tensor_.MergeFrom(from.tensor_);
  if (from.has_versions()) {
    mutable_versions()->::tensorflow::VersionDef::MergeFrom(from.versions());
  }
}

void SavedTensorSliceMeta::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SavedTensorSliceMeta::CopyFrom(const SavedTensorSliceMeta& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SavedTensorSliceMeta::IsInitialized() const {

  return true;
}

void SavedTensorSliceMeta::Swap(SavedTensorSliceMeta* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SavedTensorSliceMeta::InternalSwap(SavedTensorSliceMeta* other) {
  tensor_.UnsafeArenaSwap(&other->tensor_);
  std::swap(versions_, other->versions_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SavedTensorSliceMeta::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SavedTensorSliceMeta_descriptor_;
  metadata.reflection = SavedTensorSliceMeta_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SavedTensorSliceMeta

// repeated .tensorflow.SavedSliceMeta tensor = 1;
int SavedTensorSliceMeta::tensor_size() const {
  return tensor_.size();
}
void SavedTensorSliceMeta::clear_tensor() {
  tensor_.Clear();
}
const ::tensorflow::SavedSliceMeta& SavedTensorSliceMeta::tensor(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedTensorSliceMeta.tensor)
  return tensor_.Get(index);
}
::tensorflow::SavedSliceMeta* SavedTensorSliceMeta::mutable_tensor(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedTensorSliceMeta.tensor)
  return tensor_.Mutable(index);
}
::tensorflow::SavedSliceMeta* SavedTensorSliceMeta::add_tensor() {
  // @@protoc_insertion_point(field_add:tensorflow.SavedTensorSliceMeta.tensor)
  return tensor_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::SavedSliceMeta >*
SavedTensorSliceMeta::mutable_tensor() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.SavedTensorSliceMeta.tensor)
  return &tensor_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::SavedSliceMeta >&
SavedTensorSliceMeta::tensor() const {
  // @@protoc_insertion_point(field_list:tensorflow.SavedTensorSliceMeta.tensor)
  return tensor_;
}

// optional .tensorflow.VersionDef versions = 2;
bool SavedTensorSliceMeta::has_versions() const {
  return !_is_default_instance_ && versions_ != NULL;
}
void SavedTensorSliceMeta::clear_versions() {
  if (GetArenaNoVirtual() == NULL && versions_ != NULL) delete versions_;
  versions_ = NULL;
}
const ::tensorflow::VersionDef& SavedTensorSliceMeta::versions() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedTensorSliceMeta.versions)
  return versions_ != NULL ? *versions_ : *default_instance_->versions_;
}
::tensorflow::VersionDef* SavedTensorSliceMeta::mutable_versions() {
  
  if (versions_ == NULL) {
    versions_ = new ::tensorflow::VersionDef;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedTensorSliceMeta.versions)
  return versions_;
}
::tensorflow::VersionDef* SavedTensorSliceMeta::release_versions() {
  
  ::tensorflow::VersionDef* temp = versions_;
  versions_ = NULL;
  return temp;
}
void SavedTensorSliceMeta::set_allocated_versions(::tensorflow::VersionDef* versions) {
  delete versions_;
  versions_ = versions;
  if (versions) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedTensorSliceMeta.versions)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SavedSlice::kNameFieldNumber;
const int SavedSlice::kSliceFieldNumber;
const int SavedSlice::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SavedSlice::SavedSlice()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.SavedSlice)
}

void SavedSlice::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  slice_ = const_cast< ::tensorflow::TensorSliceProto*>(&::tensorflow::TensorSliceProto::default_instance());
  data_ = const_cast< ::tensorflow::TensorProto*>(&::tensorflow::TensorProto::default_instance());
}

SavedSlice::SavedSlice(const SavedSlice& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.SavedSlice)
}

void SavedSlice::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  slice_ = NULL;
  data_ = NULL;
}

SavedSlice::~SavedSlice() {
  // @@protoc_insertion_point(destructor:tensorflow.SavedSlice)
  SharedDtor();
}

void SavedSlice::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete slice_;
    delete data_;
  }
}

void SavedSlice::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SavedSlice::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SavedSlice_descriptor_;
}

const SavedSlice& SavedSlice::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  return *default_instance_;
}

SavedSlice* SavedSlice::default_instance_ = NULL;

SavedSlice* SavedSlice::New(::google::protobuf::Arena* arena) const {
  SavedSlice* n = new SavedSlice;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SavedSlice::Clear() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && slice_ != NULL) delete slice_;
  slice_ = NULL;
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}

bool SavedSlice::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.SavedSlice)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.SavedSlice.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_slice;
        break;
      }

      // optional .tensorflow.TensorSliceProto slice = 2;
      case 2: {
        if (tag == 18) {
         parse_slice:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_slice()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data;
        break;
      }

      // optional .tensorflow.TensorProto data = 3;
      case 3: {
        if (tag == 26) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.SavedSlice)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.SavedSlice)
  return false;
#undef DO_
}

void SavedSlice::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.SavedSlice)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.SavedSlice.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional .tensorflow.TensorSliceProto slice = 2;
  if (this->has_slice()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->slice_, output);
  }

  // optional .tensorflow.TensorProto data = 3;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->data_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.SavedSlice)
}

::google::protobuf::uint8* SavedSlice::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.SavedSlice)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.SavedSlice.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional .tensorflow.TensorSliceProto slice = 2;
  if (this->has_slice()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->slice_, target);
  }

  // optional .tensorflow.TensorProto data = 3;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *this->data_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.SavedSlice)
  return target;
}

int SavedSlice::ByteSize() const {
  int total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional .tensorflow.TensorSliceProto slice = 2;
  if (this->has_slice()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->slice_);
  }

  // optional .tensorflow.TensorProto data = 3;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SavedSlice::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SavedSlice* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SavedSlice>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SavedSlice::MergeFrom(const SavedSlice& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_slice()) {
    mutable_slice()->::tensorflow::TensorSliceProto::MergeFrom(from.slice());
  }
  if (from.has_data()) {
    mutable_data()->::tensorflow::TensorProto::MergeFrom(from.data());
  }
}

void SavedSlice::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SavedSlice::CopyFrom(const SavedSlice& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SavedSlice::IsInitialized() const {

  return true;
}

void SavedSlice::Swap(SavedSlice* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SavedSlice::InternalSwap(SavedSlice* other) {
  name_.Swap(&other->name_);
  std::swap(slice_, other->slice_);
  std::swap(data_, other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SavedSlice::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SavedSlice_descriptor_;
  metadata.reflection = SavedSlice_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SavedSlice

// optional string name = 1;
void SavedSlice::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& SavedSlice::name() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSlice.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SavedSlice::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.SavedSlice.name)
}
 void SavedSlice::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.SavedSlice.name)
}
 void SavedSlice::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.SavedSlice.name)
}
 ::std::string* SavedSlice::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSlice.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SavedSlice::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SavedSlice::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedSlice.name)
}

// optional .tensorflow.TensorSliceProto slice = 2;
bool SavedSlice::has_slice() const {
  return !_is_default_instance_ && slice_ != NULL;
}
void SavedSlice::clear_slice() {
  if (GetArenaNoVirtual() == NULL && slice_ != NULL) delete slice_;
  slice_ = NULL;
}
const ::tensorflow::TensorSliceProto& SavedSlice::slice() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSlice.slice)
  return slice_ != NULL ? *slice_ : *default_instance_->slice_;
}
::tensorflow::TensorSliceProto* SavedSlice::mutable_slice() {
  
  if (slice_ == NULL) {
    slice_ = new ::tensorflow::TensorSliceProto;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSlice.slice)
  return slice_;
}
::tensorflow::TensorSliceProto* SavedSlice::release_slice() {
  
  ::tensorflow::TensorSliceProto* temp = slice_;
  slice_ = NULL;
  return temp;
}
void SavedSlice::set_allocated_slice(::tensorflow::TensorSliceProto* slice) {
  delete slice_;
  slice_ = slice;
  if (slice) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedSlice.slice)
}

// optional .tensorflow.TensorProto data = 3;
bool SavedSlice::has_data() const {
  return !_is_default_instance_ && data_ != NULL;
}
void SavedSlice::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}
const ::tensorflow::TensorProto& SavedSlice::data() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedSlice.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
::tensorflow::TensorProto* SavedSlice::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::tensorflow::TensorProto;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedSlice.data)
  return data_;
}
::tensorflow::TensorProto* SavedSlice::release_data() {
  
  ::tensorflow::TensorProto* temp = data_;
  data_ = NULL;
  return temp;
}
void SavedSlice::set_allocated_data(::tensorflow::TensorProto* data) {
  delete data_;
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedSlice.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SavedTensorSlices::kMetaFieldNumber;
const int SavedTensorSlices::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SavedTensorSlices::SavedTensorSlices()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.SavedTensorSlices)
}

void SavedTensorSlices::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  meta_ = const_cast< ::tensorflow::SavedTensorSliceMeta*>(&::tensorflow::SavedTensorSliceMeta::default_instance());
  data_ = const_cast< ::tensorflow::SavedSlice*>(&::tensorflow::SavedSlice::default_instance());
}

SavedTensorSlices::SavedTensorSlices(const SavedTensorSlices& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.SavedTensorSlices)
}

void SavedTensorSlices::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  meta_ = NULL;
  data_ = NULL;
}

SavedTensorSlices::~SavedTensorSlices() {
  // @@protoc_insertion_point(destructor:tensorflow.SavedTensorSlices)
  SharedDtor();
}

void SavedTensorSlices::SharedDtor() {
  if (this != default_instance_) {
    delete meta_;
    delete data_;
  }
}

void SavedTensorSlices::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SavedTensorSlices::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SavedTensorSlices_descriptor_;
}

const SavedTensorSlices& SavedTensorSlices::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2futil_2fsaved_5ftensor_5fslice_2eproto();
  return *default_instance_;
}

SavedTensorSlices* SavedTensorSlices::default_instance_ = NULL;

SavedTensorSlices* SavedTensorSlices::New(::google::protobuf::Arena* arena) const {
  SavedTensorSlices* n = new SavedTensorSlices;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SavedTensorSlices::Clear() {
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) delete meta_;
  meta_ = NULL;
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}

bool SavedTensorSlices::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.SavedTensorSlices)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .tensorflow.SavedTensorSliceMeta meta = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_meta()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // optional .tensorflow.SavedSlice data = 2;
      case 2: {
        if (tag == 18) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.SavedTensorSlices)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.SavedTensorSlices)
  return false;
#undef DO_
}

void SavedTensorSlices::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.SavedTensorSlices)
  // optional .tensorflow.SavedTensorSliceMeta meta = 1;
  if (this->has_meta()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->meta_, output);
  }

  // optional .tensorflow.SavedSlice data = 2;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->data_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.SavedTensorSlices)
}

::google::protobuf::uint8* SavedTensorSlices::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.SavedTensorSlices)
  // optional .tensorflow.SavedTensorSliceMeta meta = 1;
  if (this->has_meta()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->meta_, target);
  }

  // optional .tensorflow.SavedSlice data = 2;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *this->data_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.SavedTensorSlices)
  return target;
}

int SavedTensorSlices::ByteSize() const {
  int total_size = 0;

  // optional .tensorflow.SavedTensorSliceMeta meta = 1;
  if (this->has_meta()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->meta_);
  }

  // optional .tensorflow.SavedSlice data = 2;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->data_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SavedTensorSlices::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const SavedTensorSlices* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SavedTensorSlices>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SavedTensorSlices::MergeFrom(const SavedTensorSlices& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_meta()) {
    mutable_meta()->::tensorflow::SavedTensorSliceMeta::MergeFrom(from.meta());
  }
  if (from.has_data()) {
    mutable_data()->::tensorflow::SavedSlice::MergeFrom(from.data());
  }
}

void SavedTensorSlices::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SavedTensorSlices::CopyFrom(const SavedTensorSlices& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SavedTensorSlices::IsInitialized() const {

  return true;
}

void SavedTensorSlices::Swap(SavedTensorSlices* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SavedTensorSlices::InternalSwap(SavedTensorSlices* other) {
  std::swap(meta_, other->meta_);
  std::swap(data_, other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SavedTensorSlices::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SavedTensorSlices_descriptor_;
  metadata.reflection = SavedTensorSlices_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SavedTensorSlices

// optional .tensorflow.SavedTensorSliceMeta meta = 1;
bool SavedTensorSlices::has_meta() const {
  return !_is_default_instance_ && meta_ != NULL;
}
void SavedTensorSlices::clear_meta() {
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) delete meta_;
  meta_ = NULL;
}
const ::tensorflow::SavedTensorSliceMeta& SavedTensorSlices::meta() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedTensorSlices.meta)
  return meta_ != NULL ? *meta_ : *default_instance_->meta_;
}
::tensorflow::SavedTensorSliceMeta* SavedTensorSlices::mutable_meta() {
  
  if (meta_ == NULL) {
    meta_ = new ::tensorflow::SavedTensorSliceMeta;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedTensorSlices.meta)
  return meta_;
}
::tensorflow::SavedTensorSliceMeta* SavedTensorSlices::release_meta() {
  
  ::tensorflow::SavedTensorSliceMeta* temp = meta_;
  meta_ = NULL;
  return temp;
}
void SavedTensorSlices::set_allocated_meta(::tensorflow::SavedTensorSliceMeta* meta) {
  delete meta_;
  meta_ = meta;
  if (meta) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedTensorSlices.meta)
}

// optional .tensorflow.SavedSlice data = 2;
bool SavedTensorSlices::has_data() const {
  return !_is_default_instance_ && data_ != NULL;
}
void SavedTensorSlices::clear_data() {
  if (GetArenaNoVirtual() == NULL && data_ != NULL) delete data_;
  data_ = NULL;
}
const ::tensorflow::SavedSlice& SavedTensorSlices::data() const {
  // @@protoc_insertion_point(field_get:tensorflow.SavedTensorSlices.data)
  return data_ != NULL ? *data_ : *default_instance_->data_;
}
::tensorflow::SavedSlice* SavedTensorSlices::mutable_data() {
  
  if (data_ == NULL) {
    data_ = new ::tensorflow::SavedSlice;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.SavedTensorSlices.data)
  return data_;
}
::tensorflow::SavedSlice* SavedTensorSlices::release_data() {
  
  ::tensorflow::SavedSlice* temp = data_;
  data_ = NULL;
  return temp;
}
void SavedTensorSlices::set_allocated_data(::tensorflow::SavedSlice* data) {
  delete data_;
  data_ = data;
  if (data) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.SavedTensorSlices.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
