// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/function.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/framework/function.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {

namespace {

const ::google::protobuf::Descriptor* FunctionDefLibrary_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunctionDefLibrary_reflection_ = NULL;
const ::google::protobuf::Descriptor* FunctionDef_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunctionDef_reflection_ = NULL;
const ::google::protobuf::Descriptor* FunctionDef_Node_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FunctionDef_Node_reflection_ = NULL;
const ::google::protobuf::Descriptor* FunctionDef_Node_AttrEntry_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto() {
  protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow/core/framework/function.proto");
  GOOGLE_CHECK(file != NULL);
  FunctionDefLibrary_descriptor_ = file->message_type(0);
  static const int FunctionDefLibrary_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDefLibrary, function_),
  };
  FunctionDefLibrary_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FunctionDefLibrary_descriptor_,
      FunctionDefLibrary::default_instance_,
      FunctionDefLibrary_offsets_,
      -1,
      -1,
      -1,
      sizeof(FunctionDefLibrary),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDefLibrary, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDefLibrary, _is_default_instance_));
  FunctionDef_descriptor_ = file->message_type(1);
  static const int FunctionDef_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef, signature_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef, node_),
  };
  FunctionDef_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FunctionDef_descriptor_,
      FunctionDef::default_instance_,
      FunctionDef_offsets_,
      -1,
      -1,
      -1,
      sizeof(FunctionDef),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef, _is_default_instance_));
  FunctionDef_Node_descriptor_ = FunctionDef_descriptor_->nested_type(0);
  static const int FunctionDef_Node_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, ret_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, op_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, arg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, dep_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, attr_),
  };
  FunctionDef_Node_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FunctionDef_Node_descriptor_,
      FunctionDef_Node::default_instance_,
      FunctionDef_Node_offsets_,
      -1,
      -1,
      -1,
      sizeof(FunctionDef_Node),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FunctionDef_Node, _is_default_instance_));
  FunctionDef_Node_AttrEntry_descriptor_ = FunctionDef_Node_descriptor_->nested_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FunctionDefLibrary_descriptor_, &FunctionDefLibrary::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FunctionDef_descriptor_, &FunctionDef::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FunctionDef_Node_descriptor_, &FunctionDef_Node::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
        FunctionDef_Node_AttrEntry_descriptor_,
        ::google::protobuf::internal::MapEntry<
            ::std::string,
            ::tensorflow::AttrValue,
            ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
            ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
            0>::CreateDefaultInstance(
                FunctionDef_Node_AttrEntry_descriptor_));
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_2fcore_2fframework_2ffunction_2eproto() {
  delete FunctionDefLibrary::default_instance_;
  delete FunctionDefLibrary_reflection_;
  delete FunctionDef::default_instance_;
  delete FunctionDef_reflection_;
  delete FunctionDef_Node::default_instance_;
  delete FunctionDef_Node_reflection_;
}

void protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2fattr_5fvalue_2eproto();
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fframework_2fop_5fdef_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n(tensorflow/core/framework/function.pro"
    "to\022\ntensorflow\032*tensorflow/core/framewor"
    "k/attr_value.proto\032&tensorflow/core/fram"
    "ework/op_def.proto\"\?\n\022FunctionDefLibrary"
    "\022)\n\010function\030\001 \003(\0132\027.tensorflow.Function"
    "Def\"\225\002\n\013FunctionDef\022$\n\tsignature\030\001 \001(\0132\021"
    ".tensorflow.OpDef\022*\n\004node\030\002 \003(\0132\034.tensor"
    "flow.FunctionDef.Node\032\263\001\n\004Node\022\013\n\003ret\030\001 "
    "\003(\t\022\n\n\002op\030\002 \001(\t\022\013\n\003arg\030\003 \003(\t\022\013\n\003dep\030\004 \003("
    "\t\0224\n\004attr\030\005 \003(\0132&.tensorflow.FunctionDef"
    ".Node.AttrEntry\032B\n\tAttrEntry\022\013\n\003key\030\001 \001("
    "\t\022$\n\005value\030\002 \001(\0132\025.tensorflow.AttrValue:"
    "\0028\001b\006proto3", 491);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/framework/function.proto", &protobuf_RegisterTypes);
  FunctionDefLibrary::default_instance_ = new FunctionDefLibrary();
  FunctionDef::default_instance_ = new FunctionDef();
  FunctionDef_Node::default_instance_ = new FunctionDef_Node();
  FunctionDefLibrary::default_instance_->InitAsDefaultInstance();
  FunctionDef::default_instance_->InitAsDefaultInstance();
  FunctionDef_Node::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_2fcore_2fframework_2ffunction_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_2fcore_2fframework_2ffunction_2eproto {
  StaticDescriptorInitializer_tensorflow_2fcore_2fframework_2ffunction_2eproto() {
    protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto();
  }
} static_descriptor_initializer_tensorflow_2fcore_2fframework_2ffunction_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FunctionDefLibrary::kFunctionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FunctionDefLibrary::FunctionDefLibrary()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.FunctionDefLibrary)
}

void FunctionDefLibrary::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

FunctionDefLibrary::FunctionDefLibrary(const FunctionDefLibrary& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.FunctionDefLibrary)
}

void FunctionDefLibrary::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

FunctionDefLibrary::~FunctionDefLibrary() {
  // @@protoc_insertion_point(destructor:tensorflow.FunctionDefLibrary)
  SharedDtor();
}

void FunctionDefLibrary::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FunctionDefLibrary::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunctionDefLibrary::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunctionDefLibrary_descriptor_;
}

const FunctionDefLibrary& FunctionDefLibrary::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto();
  return *default_instance_;
}

FunctionDefLibrary* FunctionDefLibrary::default_instance_ = NULL;

FunctionDefLibrary* FunctionDefLibrary::New(::google::protobuf::Arena* arena) const {
  FunctionDefLibrary* n = new FunctionDefLibrary;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FunctionDefLibrary::Clear() {
  function_.Clear();
}

bool FunctionDefLibrary::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.FunctionDefLibrary)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.FunctionDef function = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_function:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_function()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_function;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.FunctionDefLibrary)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.FunctionDefLibrary)
  return false;
#undef DO_
}

void FunctionDefLibrary::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.FunctionDefLibrary)
  // repeated .tensorflow.FunctionDef function = 1;
  for (unsigned int i = 0, n = this->function_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->function(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.FunctionDefLibrary)
}

::google::protobuf::uint8* FunctionDefLibrary::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.FunctionDefLibrary)
  // repeated .tensorflow.FunctionDef function = 1;
  for (unsigned int i = 0, n = this->function_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->function(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.FunctionDefLibrary)
  return target;
}

int FunctionDefLibrary::ByteSize() const {
  int total_size = 0;

  // repeated .tensorflow.FunctionDef function = 1;
  total_size += 1 * this->function_size();
  for (int i = 0; i < this->function_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->function(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunctionDefLibrary::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const FunctionDefLibrary* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const FunctionDefLibrary>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunctionDefLibrary::MergeFrom(const FunctionDefLibrary& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  function_.MergeFrom(from.function_);
}

void FunctionDefLibrary::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunctionDefLibrary::CopyFrom(const FunctionDefLibrary& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunctionDefLibrary::IsInitialized() const {

  return true;
}

void FunctionDefLibrary::Swap(FunctionDefLibrary* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FunctionDefLibrary::InternalSwap(FunctionDefLibrary* other) {
  function_.UnsafeArenaSwap(&other->function_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FunctionDefLibrary::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunctionDefLibrary_descriptor_;
  metadata.reflection = FunctionDefLibrary_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FunctionDefLibrary

// repeated .tensorflow.FunctionDef function = 1;
int FunctionDefLibrary::function_size() const {
  return function_.size();
}
void FunctionDefLibrary::clear_function() {
  function_.Clear();
}
const ::tensorflow::FunctionDef& FunctionDefLibrary::function(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDefLibrary.function)
  return function_.Get(index);
}
::tensorflow::FunctionDef* FunctionDefLibrary::mutable_function(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDefLibrary.function)
  return function_.Mutable(index);
}
::tensorflow::FunctionDef* FunctionDefLibrary::add_function() {
  // @@protoc_insertion_point(field_add:tensorflow.FunctionDefLibrary.function)
  return function_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::FunctionDef >*
FunctionDefLibrary::mutable_function() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.FunctionDefLibrary.function)
  return &function_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::FunctionDef >&
FunctionDefLibrary::function() const {
  // @@protoc_insertion_point(field_list:tensorflow.FunctionDefLibrary.function)
  return function_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FunctionDef_Node::kRetFieldNumber;
const int FunctionDef_Node::kOpFieldNumber;
const int FunctionDef_Node::kArgFieldNumber;
const int FunctionDef_Node::kDepFieldNumber;
const int FunctionDef_Node::kAttrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FunctionDef_Node::FunctionDef_Node()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.FunctionDef.Node)
}

void FunctionDef_Node::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

FunctionDef_Node::FunctionDef_Node(const FunctionDef_Node& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.FunctionDef.Node)
}

void FunctionDef_Node::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  op_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  attr_.SetAssignDescriptorCallback(
      protobuf_AssignDescriptorsOnce);
  attr_.SetEntryDescriptor(
      &::tensorflow::FunctionDef_Node_AttrEntry_descriptor_);
}

FunctionDef_Node::~FunctionDef_Node() {
  // @@protoc_insertion_point(destructor:tensorflow.FunctionDef.Node)
  SharedDtor();
}

void FunctionDef_Node::SharedDtor() {
  op_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void FunctionDef_Node::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunctionDef_Node::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunctionDef_Node_descriptor_;
}

const FunctionDef_Node& FunctionDef_Node::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto();
  return *default_instance_;
}

FunctionDef_Node* FunctionDef_Node::default_instance_ = NULL;

FunctionDef_Node* FunctionDef_Node::New(::google::protobuf::Arena* arena) const {
  FunctionDef_Node* n = new FunctionDef_Node;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FunctionDef_Node::Clear() {
  op_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ret_.Clear();
  arg_.Clear();
  dep_.Clear();
  attr_.Clear();
}

bool FunctionDef_Node::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.FunctionDef.Node)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string ret = 1;
      case 1: {
        if (tag == 10) {
         parse_ret:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_ret()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ret(this->ret_size() - 1).data(),
            this->ret(this->ret_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.FunctionDef.Node.ret"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_ret;
        if (input->ExpectTag(18)) goto parse_op;
        break;
      }

      // optional string op = 2;
      case 2: {
        if (tag == 18) {
         parse_op:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_op()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->op().data(), this->op().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.FunctionDef.Node.op"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_arg;
        break;
      }

      // repeated string arg = 3;
      case 3: {
        if (tag == 26) {
         parse_arg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_arg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->arg(this->arg_size() - 1).data(),
            this->arg(this->arg_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.FunctionDef.Node.arg"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_arg;
        if (input->ExpectTag(34)) goto parse_dep;
        break;
      }

      // repeated string dep = 4;
      case 4: {
        if (tag == 34) {
         parse_dep:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_dep()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dep(this->dep_size() - 1).data(),
            this->dep(this->dep_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.FunctionDef.Node.dep"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_dep;
        if (input->ExpectTag(42)) goto parse_attr;
        break;
      }

      // map<string, .tensorflow.AttrValue> attr = 5;
      case 5: {
        if (tag == 42) {
         parse_attr:
          DO_(input->IncrementRecursionDepth());
         parse_loop_attr:
          ::google::protobuf::scoped_ptr<FunctionDef_Node_AttrEntry> entry(attr_.NewEntry());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, entry.get()));
          (*mutable_attr())[entry->key()].Swap(entry->mutable_value());
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry->key().data(), entry->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.FunctionDef.Node.AttrEntry.key"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_attr;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.FunctionDef.Node)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.FunctionDef.Node)
  return false;
#undef DO_
}

void FunctionDef_Node::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.FunctionDef.Node)
  // repeated string ret = 1;
  for (int i = 0; i < this->ret_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ret(i).data(), this->ret(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.ret");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->ret(i), output);
  }

  // optional string op = 2;
  if (this->op().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->op().data(), this->op().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.op");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->op(), output);
  }

  // repeated string arg = 3;
  for (int i = 0; i < this->arg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg(i).data(), this->arg(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.arg");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->arg(i), output);
  }

  // repeated string dep = 4;
  for (int i = 0; i < this->dep_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dep(i).data(), this->dep(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.dep");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->dep(i), output);
  }

  // map<string, .tensorflow.AttrValue> attr = 5;
  {
    ::google::protobuf::scoped_ptr<FunctionDef_Node_AttrEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >::const_iterator
        it = this->attr().begin();
        it != this->attr().end(); ++it) {
      entry.reset(attr_.NewEntryWrapper(it->first, it->second));
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
          5, *entry, output);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        it->first.data(), it->first.length(),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE,
        "tensorflow.FunctionDef.Node.AttrEntry.key");
    }
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.FunctionDef.Node)
}

::google::protobuf::uint8* FunctionDef_Node::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.FunctionDef.Node)
  // repeated string ret = 1;
  for (int i = 0; i < this->ret_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ret(i).data(), this->ret(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.ret");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->ret(i), target);
  }

  // optional string op = 2;
  if (this->op().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->op().data(), this->op().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.op");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->op(), target);
  }

  // repeated string arg = 3;
  for (int i = 0; i < this->arg_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->arg(i).data(), this->arg(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.arg");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->arg(i), target);
  }

  // repeated string dep = 4;
  for (int i = 0; i < this->dep_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dep(i).data(), this->dep(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.FunctionDef.Node.dep");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->dep(i), target);
  }

  // map<string, .tensorflow.AttrValue> attr = 5;
  {
    ::google::protobuf::scoped_ptr<FunctionDef_Node_AttrEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >::const_iterator
        it = this->attr().begin();
        it != this->attr().end(); ++it) {
      entry.reset(attr_.NewEntryWrapper(it->first, it->second));
      target = ::google::protobuf::internal::WireFormatLite::
          WriteMessageNoVirtualToArray(
              5, *entry, target);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        it->first.data(), it->first.length(),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE,
        "tensorflow.FunctionDef.Node.AttrEntry.key");
    }
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.FunctionDef.Node)
  return target;
}

int FunctionDef_Node::ByteSize() const {
  int total_size = 0;

  // optional string op = 2;
  if (this->op().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->op());
  }

  // repeated string ret = 1;
  total_size += 1 * this->ret_size();
  for (int i = 0; i < this->ret_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->ret(i));
  }

  // repeated string arg = 3;
  total_size += 1 * this->arg_size();
  for (int i = 0; i < this->arg_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->arg(i));
  }

  // repeated string dep = 4;
  total_size += 1 * this->dep_size();
  for (int i = 0; i < this->dep_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->dep(i));
  }

  // map<string, .tensorflow.AttrValue> attr = 5;
  total_size += 1 * this->attr_size();
  {
    ::google::protobuf::scoped_ptr<FunctionDef_Node_AttrEntry> entry;
    for (::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >::const_iterator
        it = this->attr().begin();
        it != this->attr().end(); ++it) {
      entry.reset(attr_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunctionDef_Node::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const FunctionDef_Node* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const FunctionDef_Node>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunctionDef_Node::MergeFrom(const FunctionDef_Node& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  ret_.MergeFrom(from.ret_);
  arg_.MergeFrom(from.arg_);
  dep_.MergeFrom(from.dep_);
  attr_.MergeFrom(from.attr_);
  if (from.op().size() > 0) {

    op_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.op_);
  }
}

void FunctionDef_Node::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunctionDef_Node::CopyFrom(const FunctionDef_Node& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunctionDef_Node::IsInitialized() const {

  return true;
}

void FunctionDef_Node::Swap(FunctionDef_Node* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FunctionDef_Node::InternalSwap(FunctionDef_Node* other) {
  ret_.UnsafeArenaSwap(&other->ret_);
  op_.Swap(&other->op_);
  arg_.UnsafeArenaSwap(&other->arg_);
  dep_.UnsafeArenaSwap(&other->dep_);
  attr_.Swap(&other->attr_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FunctionDef_Node::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunctionDef_Node_descriptor_;
  metadata.reflection = FunctionDef_Node_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FunctionDef::kSignatureFieldNumber;
const int FunctionDef::kNodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FunctionDef::FunctionDef()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.FunctionDef)
}

void FunctionDef::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  signature_ = const_cast< ::tensorflow::OpDef*>(&::tensorflow::OpDef::default_instance());
}

FunctionDef::FunctionDef(const FunctionDef& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.FunctionDef)
}

void FunctionDef::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  signature_ = NULL;
}

FunctionDef::~FunctionDef() {
  // @@protoc_insertion_point(destructor:tensorflow.FunctionDef)
  SharedDtor();
}

void FunctionDef::SharedDtor() {
  if (this != default_instance_) {
    delete signature_;
  }
}

void FunctionDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FunctionDef::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FunctionDef_descriptor_;
}

const FunctionDef& FunctionDef::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_tensorflow_2fcore_2fframework_2ffunction_2eproto();
  return *default_instance_;
}

FunctionDef* FunctionDef::default_instance_ = NULL;

FunctionDef* FunctionDef::New(::google::protobuf::Arena* arena) const {
  FunctionDef* n = new FunctionDef;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FunctionDef::Clear() {
  if (GetArenaNoVirtual() == NULL && signature_ != NULL) delete signature_;
  signature_ = NULL;
  node_.Clear();
}

bool FunctionDef::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.FunctionDef)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .tensorflow.OpDef signature = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_signature()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_node;
        break;
      }

      // repeated .tensorflow.FunctionDef.Node node = 2;
      case 2: {
        if (tag == 18) {
         parse_node:
          DO_(input->IncrementRecursionDepth());
         parse_loop_node:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_node()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_node;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.FunctionDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.FunctionDef)
  return false;
#undef DO_
}

void FunctionDef::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.FunctionDef)
  // optional .tensorflow.OpDef signature = 1;
  if (this->has_signature()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->signature_, output);
  }

  // repeated .tensorflow.FunctionDef.Node node = 2;
  for (unsigned int i = 0, n = this->node_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->node(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.FunctionDef)
}

::google::protobuf::uint8* FunctionDef::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.FunctionDef)
  // optional .tensorflow.OpDef signature = 1;
  if (this->has_signature()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->signature_, target);
  }

  // repeated .tensorflow.FunctionDef.Node node = 2;
  for (unsigned int i = 0, n = this->node_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->node(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.FunctionDef)
  return target;
}

int FunctionDef::ByteSize() const {
  int total_size = 0;

  // optional .tensorflow.OpDef signature = 1;
  if (this->has_signature()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->signature_);
  }

  // repeated .tensorflow.FunctionDef.Node node = 2;
  total_size += 1 * this->node_size();
  for (int i = 0; i < this->node_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->node(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FunctionDef::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const FunctionDef* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const FunctionDef>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FunctionDef::MergeFrom(const FunctionDef& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  node_.MergeFrom(from.node_);
  if (from.has_signature()) {
    mutable_signature()->::tensorflow::OpDef::MergeFrom(from.signature());
  }
}

void FunctionDef::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FunctionDef::CopyFrom(const FunctionDef& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FunctionDef::IsInitialized() const {

  return true;
}

void FunctionDef::Swap(FunctionDef* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FunctionDef::InternalSwap(FunctionDef* other) {
  std::swap(signature_, other->signature_);
  node_.UnsafeArenaSwap(&other->node_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FunctionDef::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FunctionDef_descriptor_;
  metadata.reflection = FunctionDef_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FunctionDef_Node

// repeated string ret = 1;
int FunctionDef_Node::ret_size() const {
  return ret_.size();
}
void FunctionDef_Node::clear_ret() {
  ret_.Clear();
}
 const ::std::string& FunctionDef_Node::ret(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.Node.ret)
  return ret_.Get(index);
}
 ::std::string* FunctionDef_Node::mutable_ret(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.Node.ret)
  return ret_.Mutable(index);
}
 void FunctionDef_Node::set_ret(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tensorflow.FunctionDef.Node.ret)
  ret_.Mutable(index)->assign(value);
}
 void FunctionDef_Node::set_ret(int index, const char* value) {
  ret_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.FunctionDef.Node.ret)
}
 void FunctionDef_Node::set_ret(int index, const char* value, size_t size) {
  ret_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.FunctionDef.Node.ret)
}
 ::std::string* FunctionDef_Node::add_ret() {
  return ret_.Add();
}
 void FunctionDef_Node::add_ret(const ::std::string& value) {
  ret_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.FunctionDef.Node.ret)
}
 void FunctionDef_Node::add_ret(const char* value) {
  ret_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.FunctionDef.Node.ret)
}
 void FunctionDef_Node::add_ret(const char* value, size_t size) {
  ret_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.FunctionDef.Node.ret)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
FunctionDef_Node::ret() const {
  // @@protoc_insertion_point(field_list:tensorflow.FunctionDef.Node.ret)
  return ret_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
FunctionDef_Node::mutable_ret() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.FunctionDef.Node.ret)
  return &ret_;
}

// optional string op = 2;
void FunctionDef_Node::clear_op() {
  op_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& FunctionDef_Node::op() const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.Node.op)
  return op_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void FunctionDef_Node::set_op(const ::std::string& value) {
  
  op_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.FunctionDef.Node.op)
}
 void FunctionDef_Node::set_op(const char* value) {
  
  op_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.FunctionDef.Node.op)
}
 void FunctionDef_Node::set_op(const char* value, size_t size) {
  
  op_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.FunctionDef.Node.op)
}
 ::std::string* FunctionDef_Node::mutable_op() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.Node.op)
  return op_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* FunctionDef_Node::release_op() {
  
  return op_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void FunctionDef_Node::set_allocated_op(::std::string* op) {
  if (op != NULL) {
    
  } else {
    
  }
  op_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), op);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.FunctionDef.Node.op)
}

// repeated string arg = 3;
int FunctionDef_Node::arg_size() const {
  return arg_.size();
}
void FunctionDef_Node::clear_arg() {
  arg_.Clear();
}
 const ::std::string& FunctionDef_Node::arg(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.Node.arg)
  return arg_.Get(index);
}
 ::std::string* FunctionDef_Node::mutable_arg(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.Node.arg)
  return arg_.Mutable(index);
}
 void FunctionDef_Node::set_arg(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tensorflow.FunctionDef.Node.arg)
  arg_.Mutable(index)->assign(value);
}
 void FunctionDef_Node::set_arg(int index, const char* value) {
  arg_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.FunctionDef.Node.arg)
}
 void FunctionDef_Node::set_arg(int index, const char* value, size_t size) {
  arg_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.FunctionDef.Node.arg)
}
 ::std::string* FunctionDef_Node::add_arg() {
  return arg_.Add();
}
 void FunctionDef_Node::add_arg(const ::std::string& value) {
  arg_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.FunctionDef.Node.arg)
}
 void FunctionDef_Node::add_arg(const char* value) {
  arg_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.FunctionDef.Node.arg)
}
 void FunctionDef_Node::add_arg(const char* value, size_t size) {
  arg_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.FunctionDef.Node.arg)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
FunctionDef_Node::arg() const {
  // @@protoc_insertion_point(field_list:tensorflow.FunctionDef.Node.arg)
  return arg_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
FunctionDef_Node::mutable_arg() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.FunctionDef.Node.arg)
  return &arg_;
}

// repeated string dep = 4;
int FunctionDef_Node::dep_size() const {
  return dep_.size();
}
void FunctionDef_Node::clear_dep() {
  dep_.Clear();
}
 const ::std::string& FunctionDef_Node::dep(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.Node.dep)
  return dep_.Get(index);
}
 ::std::string* FunctionDef_Node::mutable_dep(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.Node.dep)
  return dep_.Mutable(index);
}
 void FunctionDef_Node::set_dep(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tensorflow.FunctionDef.Node.dep)
  dep_.Mutable(index)->assign(value);
}
 void FunctionDef_Node::set_dep(int index, const char* value) {
  dep_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.FunctionDef.Node.dep)
}
 void FunctionDef_Node::set_dep(int index, const char* value, size_t size) {
  dep_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.FunctionDef.Node.dep)
}
 ::std::string* FunctionDef_Node::add_dep() {
  return dep_.Add();
}
 void FunctionDef_Node::add_dep(const ::std::string& value) {
  dep_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.FunctionDef.Node.dep)
}
 void FunctionDef_Node::add_dep(const char* value) {
  dep_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.FunctionDef.Node.dep)
}
 void FunctionDef_Node::add_dep(const char* value, size_t size) {
  dep_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.FunctionDef.Node.dep)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
FunctionDef_Node::dep() const {
  // @@protoc_insertion_point(field_list:tensorflow.FunctionDef.Node.dep)
  return dep_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
FunctionDef_Node::mutable_dep() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.FunctionDef.Node.dep)
  return &dep_;
}

// map<string, .tensorflow.AttrValue> attr = 5;
int FunctionDef_Node::attr_size() const {
  return attr_.size();
}
void FunctionDef_Node::clear_attr() {
  attr_.Clear();
}
 const ::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >&
FunctionDef_Node::attr() const {
  // @@protoc_insertion_point(field_map:tensorflow.FunctionDef.Node.attr)
  return attr_.GetMap();
}
 ::google::protobuf::Map< ::std::string, ::tensorflow::AttrValue >*
FunctionDef_Node::mutable_attr() {
  // @@protoc_insertion_point(field_mutable_map:tensorflow.FunctionDef.Node.attr)
  return attr_.MutableMap();
}

// -------------------------------------------------------------------

// FunctionDef

// optional .tensorflow.OpDef signature = 1;
bool FunctionDef::has_signature() const {
  return !_is_default_instance_ && signature_ != NULL;
}
void FunctionDef::clear_signature() {
  if (GetArenaNoVirtual() == NULL && signature_ != NULL) delete signature_;
  signature_ = NULL;
}
const ::tensorflow::OpDef& FunctionDef::signature() const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.signature)
  return signature_ != NULL ? *signature_ : *default_instance_->signature_;
}
::tensorflow::OpDef* FunctionDef::mutable_signature() {
  
  if (signature_ == NULL) {
    signature_ = new ::tensorflow::OpDef;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.signature)
  return signature_;
}
::tensorflow::OpDef* FunctionDef::release_signature() {
  
  ::tensorflow::OpDef* temp = signature_;
  signature_ = NULL;
  return temp;
}
void FunctionDef::set_allocated_signature(::tensorflow::OpDef* signature) {
  delete signature_;
  signature_ = signature;
  if (signature) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.FunctionDef.signature)
}

// repeated .tensorflow.FunctionDef.Node node = 2;
int FunctionDef::node_size() const {
  return node_.size();
}
void FunctionDef::clear_node() {
  node_.Clear();
}
const ::tensorflow::FunctionDef_Node& FunctionDef::node(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.FunctionDef.node)
  return node_.Get(index);
}
::tensorflow::FunctionDef_Node* FunctionDef::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.FunctionDef.node)
  return node_.Mutable(index);
}
::tensorflow::FunctionDef_Node* FunctionDef::add_node() {
  // @@protoc_insertion_point(field_add:tensorflow.FunctionDef.node)
  return node_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::FunctionDef_Node >*
FunctionDef::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.FunctionDef.node)
  return &node_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::FunctionDef_Node >&
FunctionDef::node() const {
  // @@protoc_insertion_point(field_list:tensorflow.FunctionDef.node)
  return node_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
